OUTPUT_DIR: ""
INPUT:
  TDATASET: "CUHK-SYSU"
  DATASET: "PRW"
  TDATA_ROOT: ""
  DATA_ROOT: ""
  BATCH_SIZE_TRAIN: 4
SOLVER:
  MAX_EPOCHS: 14
  BASE_LR: 0.0024
  LW_BOX_REID_T: 0.5
MODEL:
  DA_HEADS:
    DA_IMG_LOSS_WEIGHT: 1.0
    DA_INS_LOSS_WEIGHT: 1.0
    DA_CST_LOSS_WEIGHT: 0.1
  UPDATE_FACTOR:
    ONLINE: 0.2
    OFFLINE: 0.2
EVAL_PERIOD: 1
TARGET_REID_START: 3
EPS_P: 0.95
HM_THRESH: 0.3
